env:
    CIRRUS_CLONE_DEPTH: 1
    rom_name: nusa
    device: lavender

task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: snaxpsycho/cirrus:latest
      # image: snaxpsycho/cirrus:alpha
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  notify_script:
    - rm -rf /usr/local/bin/repo
    - sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
    - sudo chmod a+rx /usr/local/bin/repo
    - bash <(curl -s $script/notify.sh)
    
  sync_script:
    - bash <(curl -s $script/sync.sh)
    
  vanilla_build_script:
    - bash <(curl -s $script/build.sh)
    
  # apps_up_script:
    # - set -e
    # - bash $CIRRUS_WORKING_DIR/upload_apps.sh
    # - bash <(curl -s $script/upload_apps.sh)
    
  # gapps_build_script:
    # - set -e
    # - bash <(curl -s $script/gapps_build.sh)
    
  # gapps_up_script:
    # - set -e
    # - bash <(curl -s $script/sfg_uploader.sh)
