env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: Matrixx
    device: lavender

task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  notify_script:
    - bash <(curl -s $script/notify.sh)
    
  tsync_script:
    - sudo apt update -y && sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
    - rm -rf ~/bin/repo
    - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod a+x ~/bin/repo
    
  sync_script:
    - bash <(curl -s $script/sync.sh)
    
  vanilla_build_script:
    - bash <(curl -s $script/build.sh)
    
  # apps_up_script:
    # - set -e
    # - bash <(curl -s $script/upload_apps.sh)
    
  # gapps_build_script:
    # - set -e
    # - bash <(curl -s $script/gapps_build.sh)
    
  # gapps_up_script:
    # - set -e
    # - bash <(curl -s $script/sfg_uploader.sh)
