env:
    CIRRUS_CLONE_DEPTH: 1
    rom_name: Cr
    device: lavender
    TELEGRAM_ID: $tg_id
    BOT_API: $bot_api

task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: snaxpsycho/crave:ubuntu
      # image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  update_script:
    - sudo apt update -y
    - sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 jq libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git-lfs -y

  sync_script:
    - mkdir Cr && cd Cr
    - repo init -u https://github.com/crDroid-Revived/android.git -b 11.0 --git-lfs
    - git clone git@github.com:Snax-phycho/manifest.git --depth 1 -b cr .repo/local_manifests
    - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --prune

  compile_script:
    - bash $CIRRUS_WORKING_DIR/cr.sh
    