env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: Nusantara
    device: lavender

task:
  name: "Snx-xR"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: ubuntu:latest
      # image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
        
  tsync_script:
    - set -e
    - apt update
    - apt install sudo
    - sudo apt update -y && sudo apt install git aria2 openssh curl wget rsync zip unzip lzma cpio ccache clang -y
    - bash <(curl -s $script/tsync.sh)
  
  snotify_script:
    - set -e
    - bash <(curl -s $script/notify.sh)
    
  ssync_script:
    - set -e
    - bash <(curl -s $script/sync.sh)

  vanilla_build_script:
    - bash <(curl -s $script/build.sh)
    
  apps_up_script:
    - set -e
    - bash <(curl -s $script/upload_apps.sh)
    
  # gapps_build_script:
    # - set -e
    # - bash <(curl -s $script/gapps_build.sh)
    
  # gapps_up_script:
    # - set -e
    # - bash <(curl -s $script/sfg_uploader.sh)
