env:
    CIRRUS_CLONE_DEPTH: 1
    rom: Qassa
    device: lavender
    TELEGRAM_ID: $tg_id
    BOT_API: $bot_api

task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  repo_script:
    - mkdir $rom
    - rm /usr/local/bin/repo
    - sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
    - sudo chmod a+rx /usr/local/bin/repo
    
  compiling_script:
    - cd $rom
    - git clone https://Snax-phycho:$ght@github.com/Snax-phycho/Snx -b cirrus
    - bash Snx/build.sh --sync -sf

  dirs_script:
    - cd $rom
    - curl -O https://raw.githubusercontent.com/Sushrut1101/GoFile-Upload/refs/heads/master/upload.sh
    - bash upload.sh out/target/product/$device/*.zip
    - echo -e "done"
    