env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: Nusantara
    device: lavender

task:
  name: "Snx-xR"
  # skip: $CIRRUS_BRANCH == 'main'
  # timeout_in: 240m
  container:
      # image: ubuntu:latest
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  vanilla_build_script:
    - repo init --depth=1 --no-repo-verify -u https://Sa-Sajjad:$ght@github.com/S-A-build/android_manifest_nusa.git -b battery -g default,-mips,-darwin,-notdefault
    - repo status
    - repo start 10 --all
    - git clone git@github.com:Sa-Sajjad/manifest.git --depth 1 -b hmp2 .repo/local_manifests
    # - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    - bash <(curl -s $script/notify.sh)
    - repo sync
    # - bash <(curl -s $script/sync.sh)
    - bash <(curl -s $script/build.sh)
    
  # apps_up_script:
    # - set -e
    # - bash <(curl -s $script/upload_apps.sh)
    
  # gapps_build_script:
    # - set -e
    # - bash <(curl -s $script/gapps_build.sh)
    
  # gapps_up_script:
    # - set -e
    # - bash <(curl -s $script/sfg_uploader.sh)
