env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: Nusantara
    device: lavender

task:
  name: "Snx-R"
  timeout_in: 240m
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  notify_script:
    - apt update
    - sudo apt update -y
    - bash <(curl -s $script/notify.sh)
    
  sync_script:
    - bash <(curl -s $script/sync.sh)
    
  vanilla_build_script:
    - bash <(curl -s $script/build.sh)
    
  # apps_up_script:
    # - set -e
    # - bash <(curl -s $script/upload_apps.sh)
    
  # gapps_build_script:
    # - set -e
    # - bash <(curl -s $script/gapps_build.sh)
    
  # gapps_up_script:
    # - set -e
    # - bash <(curl -s $script/sfg_uploader.sh)
