env:
    CIRRUS_CLONE_DEPTH: 1
    device: lavender
    TELEGRAM_ID: $tg_id
    BOT_API: $bot_api
    
task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  build_script:
    - mkdir -p Crdroid
    - cd Crdroid
    - git clone https://Snax-phycho:$ght@github.com/Snax-phycho/Snx -b cr
    - bash Snx/build.sh --sync --gofile
  