env:
    CIRRUS_CLONE_DEPTH: 1
    rom_name: Nusantara
    device: lavender
    snx: $CIRRUS_WORKING_DIR/Snx-R/snx

task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  twrp_script:
    - bash $CIRRUS_WORKING_DIR/ofx.sh
