env:
    CIRRUS_CLONE_DEPTH: 1
    device: lavender
    TELEGRAM_ID: $tg_id
    BOT_API: $bot_api
    
task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: snaxpsycho/crave:ubuntu
      # image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  space_script:
    - mkdir -p Crdroid
    - df -h .

  build_script:
    - cd Crdroid
    - repo init -u https://github.com/LineageOS/android.git -b lineage-22.1 --git-lfs
    # - git clone git@github.com:Snax-phycho/manifest.git --depth 1 -b cr-14 .repo/local_manifests
    - repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune

  source_script:
    - cd Crdroid
    - echo -e "Cloning device tree"
    - git clone git@github.com:Sa-Sajjad/device_xiaomi_lavender-4.19.git -b wip device/xiaomi/lavender
    - echo -e "Cloning vendor tree"
    - git clone git@github.com:Sa-Sajjad/vendor_xiaomi_lavender-4.19.git -b 14.0 vendor/xiaomi/lavender
    - echo -e "Cloning kernel tree"
    - git clone git@github.com:Sa-Sajjad/kernel_xiaomi_lavender-4.19.git -b 15.0 kernel/xiaomi/lavender --depth 10
    - echo -e "Cloning recommend hals"
    - rm -rf -v hardware/qcom-caf/msm8998/au* hardware/qcom-caf/msm8998/me* hardware/qcom-caf/msm8998/di* hardware/xiaomi
    - git clone https://github.com/Sa-Sajjad/android_hardware_qcom_display -b 15.0 hardware/qcom-caf/msm8998/display
    - git clone https://github.com/Sa-Sajjad/android_hardware_qcom_audio -b 15.0 hardware/qcom-caf/msm8998/audio
    - git clone https://github.com/Sa-Sajjad/android_hardware_qcom_media -b 15.0 hardware/qcom-caf/msm8998/media
    - git clone git@github.com:Sa-Sajjad/vendor_signkeys vendor/extra
    - git clone https://github.com/LineageOS/android_hardware_xiaomi -b lineage-22.1 hardware/xiaomi

  compile_script:
    - cd Crdroid
    - source build/envsetup.sh && breakfast lavender && brunch lavender
    