env:
    CIRRUS_CLONE_DEPTH: 1
    rom_name: Nusantara
    device: lavender
    TELEGRAM_ID: $tg_id
    BOT_API: $bot_api

task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 240m
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  repo_script:
    - mkdir Qassa
    - df -h .
    - repo --version
    - cd .repo/repo
    - git pull -r
    - cd -
    - repo --version
    
  compiling_script:
    - cd Qassa
    - git clone https://Snax-phycho:$ght@github.com/Snax-phycho/Snx -b cirrus
    - bash Snx/build.sh --sync -sf

task:
  name: "upload on gofile"
  depends_on: Snx-R
  timeout_in: 10m
  container:
      image: snaxpsycho/crave:ubuntu
      cpu: 4
      memory: 16G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  dirs_script:
    - cd Qassa
    - curl -O https://raw.githubusercontent.com/Sushrut1101/GoFile-Upload/refs/heads/master/upload.sh
    - bash upload.sh out/target/product/$device/*.zip