env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: Matrixx
    device: lavender

task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 200m
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  notify_script:
    - rm -rf /usr/local/bin/repo
    - sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
    - sudo chmod a+rx /usr/local/bin/repo
    - bash <(curl -s $script/notify.sh)
    
  sync_script:
    - mkdir ~/$rom_name
    - cd ~/$rom_name
    - repo init --depth=1 --no-repo-verify --git-lfs -u https://github.com/ProjectMatrixx/android.git -b 14.0 -g default,-mips,-darwin,-notdefault
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    
  trees_script:
    - cd ~/$rom_name
    - git clone --depth 1 https://Sa-Sajjad:$ght@github.com/Sa-Sajjad/device_xiaomi_lavender-14 -b matrix device/xiaomi/lavender
    - git clone --depth 1 https://github.com/Sa-Sajjad/vendor_xiaomi_lavender -b matrix-14 vendor/xiaomi/lavender
    - git clone --depth 1 https://github.com/Sa-Sajjad/kernel_xiaomi_lavender-neko -b neko-qti kernel/xiaomi/lavender

  # sync_script:
    # - bash <(curl -s $script/sync.sh)
  
  lunch_script:
    - cd ~/$rom_name
    - export CCACHE_DIR=~/ccache/$rom_name/$device
    - export CCACHE_EXEC=$(which ccache)
    - export USE_CCACHE=1
    - ccache -M 25G
    - ccache -z
    - source build/envsetup.sh
    - lunch lineage_lavender-userdebug
    
  lunch2_script:
    - cd ~/$rom_name
    - export TZ=Asia/Dhaka
    - export SELINUX_IGNORE_NEVERALLOWS=true
    - export RELAX_USES_LIBRARY_CHECK=true
    - export SKIP_ABI_CHECKS=true
    - export BUILD_BROKEN_VERIFY_USES_LIBRARIES=true
    - export RELAX_USES_LIBRARY_CHECK=true
    - make api-stubs-docs || echo no problem
    
  lunch3_script:
    - cd ~/$rom_name
    - export TZ=Asia/Dhaka
    - export SELINUX_IGNORE_NEVERALLOWS=true
    - export RELAX_USES_LIBRARY_CHECK=true
    - export SKIP_ABI_CHECKS=true
    - export BUILD_BROKEN_VERIFY_USES_LIBRARIES=true
    - export RELAX_USES_LIBRARY_CHECK=true
    - make system-api-stubs-docs || echo no problem
    
  lunch4_script:
    - cd ~/$rom_name
    - export TZ=Asia/Dhaka
    - export SELINUX_IGNORE_NEVERALLOWS=true
    - export RELAX_USES_LIBRARY_CHECK=true
    - export SKIP_ABI_CHECKS=true
    - export BUILD_BROKEN_VERIFY_USES_LIBRARIES=true
    - export RELAX_USES_LIBRARY_CHECK=true
    - make test-api-stubs-docs || echo no problem
  
  # lunch4_script:
    # - cd ~/$rom_name
    # - export TZ=Asia/Dhaka
    # - export SELINUX_IGNORE_NEVERALLOWS=true
    # - export RELAX_USES_LIBRARY_CHECK=true
    # - export SKIP_ABI_CHECKS=true
    # - export BUILD_BROKEN_VERIFY_USES_LIBRARIES=true
    # - export RELAX_USES_LIBRARY_CHECK=true
    # - m bacon

  vanilla_build_script:
    - bash <(curl -s $script/build.sh)
    
  # apps_up_script:
    # - set -e
    # - bash <(curl -s $script/upload_apps.sh)
    
  # gapps_build_script:
    # - set -e
    # - bash <(curl -s $script/gapps_build.sh)
    
  # gapps_up_script:
    # - set -e
    # - bash <(curl -s $script/sfg_uploader.sh)
